### ISSUE TITLE
it doesn't work

### ISSUE THREAD

**Issue by 7JEO** [devJimmyboy/Chatting#1]
i installed it and when i launch it nothing happens.

**Comment by devJimmyboy** [comment]
LMFAO

its more of a personal project, but the controls are as follows:

### Keybinds
- `F9` : **Toggles between showing the window and toggles mouse/keyboard interaction**
- `TAB`: **Autocompletes current input with emotes in chat or a command**

### Commands
- `/login` : **Starts the login process to Twitch**
- `/join {channel}` : **Joins the channel specified, must be logged in**

## Important Note
This project is unfinished, and probably will be for a while.
The settings button doesn't work, sub emotes and chatter names don't autocomplete, and probably a few more issues I can't find the time to implement.

Other than that, thanks for looking into this!
